#pragma once
#include <SpehsEngine/Core/Log.h>
#include <SpehsEngine/Core/Color.h>
#include <SpehsEngine/Core/Vector.h>
#include <SpehsEngine/Core/Time.h>
#include <SpehsEngine/Rendering/Polygon.h>
#include <SpehsEngine/Rendering/Text.h>
#include <SpehsEngine/Rendering/BatchManager.h>
#include "GUIRectangle.h"
#include "GUIRectangleContainer.h"